version: '3.8'

services:
  aerodrift-engine:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: aerodrift-engine
    restart: "no"
    ports:
      - "8000:8000"
    volumes:
      - ./logs:/app/logs

  aerodrift-dashboard:
    build:
      context: .
      dockerfile: frontend.Dockerfile
    container_name: aerodrift-dashboard
    ports:
      - "8501:8501"
    depends_on:
      - aerodrift-engine
