version: '3.8'

services:
  aerodrift-engine:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: aerodrift-engine
    restart: "no"
    ports:
      - "8000:8000"
    volumes:
      - ./logs:/app/logs
